# Python stubs generated by omniidl from idl/rag.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "rag"
#
__name__ = "rag"
_0_rag = omniORB.openModule("rag", r"idl/rag.idl")
_0_rag__POA = omniORB.openModule("rag__POA", r"idl/rag.idl")


# interface Worker
_0_rag._d_Worker = (omniORB.tcInternal.tv_objref, "IDL:rag/Worker:1.0", "Worker")
omniORB.typeMapping["IDL:rag/Worker:1.0"] = _0_rag._d_Worker
_0_rag.Worker = omniORB.newEmptyClass()
class Worker :
    _NP_RepositoryId = _0_rag._d_Worker[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_rag.Worker = Worker
_0_rag._tc_Worker = omniORB.tcInternal.createTypeCode(_0_rag._d_Worker)
omniORB.registerType(Worker._NP_RepositoryId, _0_rag._d_Worker, _0_rag._tc_Worker)

# Worker operations and attributes
Worker._d_ping = ((), (), None)
Worker._d_processFile = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), None)

# Worker object reference
class _objref_Worker (CORBA.Object):
    _NP_RepositoryId = Worker._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def ping(self, *args):
        return self._obj.invoke("ping", _0_rag.Worker._d_ping, args)

    def processFile(self, *args):
        return self._obj.invoke("processFile", _0_rag.Worker._d_processFile, args)

omniORB.registerObjref(Worker._NP_RepositoryId, _objref_Worker)
_0_rag._objref_Worker = _objref_Worker
del Worker, _objref_Worker

# Worker skeleton
__name__ = "rag__POA"
class Worker (PortableServer.Servant):
    _NP_RepositoryId = _0_rag.Worker._NP_RepositoryId


    _omni_op_d = {"ping": _0_rag.Worker._d_ping, "processFile": _0_rag.Worker._d_processFile}

Worker._omni_skeleton = Worker
_0_rag__POA.Worker = Worker
omniORB.registerSkeleton(Worker._NP_RepositoryId, Worker)
del Worker
__name__ = "rag"

#
# End of module "rag"
#
__name__ = "rag_idl"

_exported_modules = ( "rag", )

# The end.
