# DO NOT EDIT THIS FILE!
#
# Python module rag__POA generated by omniidl

import omniORB
omniORB.updateModule("rag__POA")

# ** 1. Stub files contributing to this module
import rag_idl

# ** 2. Sub-modules

# ** 3. End
