package edu.yourorg.msr.graphrag.ingestion

import edu.yourorg.msr.graphrag.core.Logging
import edu.yourorg.msr.graphrag.core.model._

import java.io.{File, PrintWriter}
import java.security.MessageDigest
import java.nio.charset.StandardCharsets
import scala.io.Source
import scala.util.Try

/**
 * MSRCorpus Processor
 * 
 * Processes text files from the MSRCorpus dataset and generates
 * chunk TSV files for the GraphRAG pipeline.
 * 
 * This utility:
 *   1. Reads text files from a directory
 *   2. Splits them into chunks of configurable size
 *   3. Computes stable IDs using SHA-256
 *   4. Outputs a TSV file in the format expected by FlinkGraphRagJob
 * 
 * Usage:
 *   sbt "ingestion/runMain edu.yourorg.msr.graphrag.ingestion.MSRCorpusProcessor \
 *        --input /path/to/msr/texts --output /path/to/chunks.tsv"
 */
object MSRCorpusProcessor extends Logging {

  // Default chunk size (characters)
  private val DefaultChunkSize = 1000
  // Overlap between chunks to preserve context
  private val DefaultOverlap = 100

  def main(args: Array[String]): Unit = {
    logger.info("=" * 60)
    logger.info("MSRCorpus Processor - Chunk Generation")
    logger.info("=" * 60)

    // Parse arguments
    val argMap = parseArgs(args)
    
    val inputDir = argMap.getOrElse("input", {
      logger.error("Missing --input argument. Usage: --input <dir> --output <file>")
      sys.exit(1)
    })
    
    val outputFile = argMap.getOrElse("output", "data/msr_chunks.tsv")
    val chunkSize = argMap.get("chunkSize").map(_.toInt).getOrElse(DefaultChunkSize)
    val overlap = argMap.get("overlap").map(_.toInt).getOrElse(DefaultOverlap)

    logger.info(s"Input directory: $inputDir")
    logger.info(s"Output file: $outputFile")
    logger.info(s"Chunk size: $chunkSize chars, overlap: $overlap chars")

    processDirectory(inputDir, outputFile, chunkSize, overlap)
  }

  /**
   * Process all text files in a directory and generate chunks.
   */
  def processDirectory(
    inputDir: String,
    outputFile: String,
    chunkSize: Int,
    overlap: Int
  ): Unit = {
    val dir = new File(inputDir)
    
    if (!dir.exists() || !dir.isDirectory) {
      logger.error(s"Input directory does not exist: $inputDir")
      return
    }

    // Find all text files (recursively)
    val textFiles = findTextFiles(dir)
    logger.info(s"Found ${textFiles.size} text files to process")

    if (textFiles.isEmpty) {
      logger.warn("No text files found. Looking for .txt, .text, or .md files.")
      return
    }

    // Process files and generate chunks
    val writer = new PrintWriter(new File(outputFile))
    
    try {
      // Write header comment
      writer.println("# GraphRAG Chunk File - Generated by MSRCorpusProcessor")
      writer.println("# Format: chunkId\\tdocId\\tchunkIx\\tstartPos\\tendPos\\tsectionPath\\ttext\\tsourceUri\\tcontentHash\\tlanguage")
      
      var totalChunks = 0
      
      textFiles.zipWithIndex.foreach { case (file, fileIdx) =>
        logger.info(s"Processing [${fileIdx + 1}/${textFiles.size}]: ${file.getName}")
        
        val chunks = processFile(file, chunkSize, overlap)
        chunks.foreach { chunk =>
          writer.println(chunkToTsv(chunk))
          totalChunks += 1
        }
      }
      
      logger.info(s"Generated $totalChunks chunks from ${textFiles.size} files")
      logger.info(s"Output written to: $outputFile")
      
    } finally {
      writer.close()
    }
  }

  /**
   * Process a single text file into chunks.
   */
  def processFile(file: File, chunkSize: Int, overlap: Int): List[Chunk] = {
    val text = Try(Source.fromFile(file, "UTF-8").mkString).getOrElse {
      // Fallback to ISO-8859-1 for files with encoding issues
      Try(Source.fromFile(file, "ISO-8859-1").mkString).getOrElse("")
    }
    
    if (text.isEmpty) {
      logger.warn(s"Empty or unreadable file: ${file.getName}")
      return Nil
    }

    val docId = computeDocId(file)
    val sourceUri = file.toURI.toString
    
    // Normalize text
    val normalizedText = normalizeText(text)
    
    // Split into chunks
    splitIntoChunks(normalizedText, chunkSize, overlap).zipWithIndex.map { case ((chunkText, startPos, endPos), idx) =>
      val contentHash = sha256(chunkText)
      val chunkId = computeChunkId(docId, startPos, endPos, contentHash)
      
      Chunk(
        chunkId = chunkId,
        docId = docId,
        chunkIx = idx,
        startPos = startPos,
        endPos = endPos,
        sectionPath = extractSectionPath(file, idx),
        text = chunkText,
        sourceUri = sourceUri,
        contentHash = contentHash,
        language = Some("en") // Assume English for MSRCorpus
      )
    }
  }

  /**
   * Split text into overlapping chunks.
   */
  private def splitIntoChunks(
    text: String,
    chunkSize: Int,
    overlap: Int
  ): List[(String, Int, Int)] = {
    if (text.length <= chunkSize) {
      return List((text, 0, text.length))
    }

    val chunks = scala.collection.mutable.ListBuffer[(String, Int, Int)]()
    var start = 0
    
    while (start < text.length) {
      val end = math.min(start + chunkSize, text.length)
      
      // Try to break at a sentence or word boundary
      val adjustedEnd = if (end < text.length) {
        findBreakPoint(text, end, start + chunkSize / 2)
      } else {
        end
      }
      
      val chunkText = text.substring(start, adjustedEnd).trim
      if (chunkText.nonEmpty) {
        chunks += ((chunkText, start, adjustedEnd))
      }
      
      // Move start, accounting for overlap
      start = adjustedEnd - overlap
      if (start <= chunks.lastOption.map(_._1.length).getOrElse(0) - overlap) {
        start = adjustedEnd // Prevent infinite loop
      }
    }
    
    chunks.toList
  }

  /**
   * Find a good break point (sentence end or word boundary).
   */
  private def findBreakPoint(text: String, targetEnd: Int, minEnd: Int): Int = {
    // Look for sentence boundaries
    val sentenceEnds = List('.', '!', '?')
    
    // Search backwards from targetEnd for a sentence boundary
    var pos = targetEnd
    while (pos > minEnd) {
      if (sentenceEnds.contains(text.charAt(pos - 1)) && 
          (pos >= text.length || text.charAt(pos).isWhitespace)) {
        return pos
      }
      pos -= 1
    }
    
    // Fall back to word boundary
    pos = targetEnd
    while (pos > minEnd && !text.charAt(pos - 1).isWhitespace) {
      pos -= 1
    }
    
    if (pos > minEnd) pos else targetEnd
  }

  /**
   * Normalize text for consistent processing.
   */
  private def normalizeText(text: String): String = {
    text
      .replaceAll("\\r\\n", "\n")
      .replaceAll("\\r", "\n")
      .replaceAll("[ \\t]+", " ")
      .replaceAll("\\n{3,}", "\n\n")
      .trim
  }

  /**
   * Find all text files recursively.
   */
  private def findTextFiles(dir: File): List[File] = {
    val extensions = Set(".txt", ".text", ".md")
    
    dir.listFiles().toList.flatMap { file =>
      if (file.isDirectory) {
        findTextFiles(file)
      } else if (extensions.exists(file.getName.toLowerCase.endsWith)) {
        List(file)
      } else {
        Nil
      }
    }
  }

  /**
   * Compute document ID from file path.
   */
  private def computeDocId(file: File): String = {
    s"doc:${sha256(file.getAbsolutePath).take(16)}"
  }

  /**
   * Compute chunk ID from doc, span, and hash.
   */
  private def computeChunkId(docId: String, start: Int, end: Int, hash: String): String = {
    s"chunk:${sha256(s"$docId:$start:$end:$hash").take(16)}"
  }

  /**
   * Extract section path from filename and index.
   */
  private def extractSectionPath(file: File, chunkIdx: Int): Option[String] = {
    val baseName = file.getName.replaceAll("\\.[^.]+$", "")
    Some(s"$baseName/chunk_$chunkIdx")
  }

  /**
   * Convert chunk to TSV line.
   */
  private def chunkToTsv(chunk: Chunk): String = {
    val escapedText = chunk.text
      .replace("\t", " ")
      .replace("\n", " ")
      .replace("\r", "")
    
    List(
      chunk.chunkId,
      chunk.docId,
      chunk.chunkIx.toString,
      chunk.startPos.toString,
      chunk.endPos.toString,
      chunk.sectionPath.getOrElse(""),
      escapedText,
      chunk.sourceUri,
      chunk.contentHash,
      chunk.language.getOrElse("en")
    ).mkString("\t")
  }

  /**
   * Compute SHA-256 hash.
   */
  private def sha256(input: String): String = {
    val digest = MessageDigest.getInstance("SHA-256")
    val hash = digest.digest(input.getBytes(StandardCharsets.UTF_8))
    hash.map("%02x".format(_)).mkString
  }

  /**
   * Parse command line arguments.
   */
  private def parseArgs(args: Array[String]): Map[String, String] = {
    args.sliding(2, 2).collect {
      case Array(key, value) if key.startsWith("--") =>
        key.stripPrefix("--") -> value
    }.toMap
  }
}

