import sys, os, time, json, logging, logging.config, yaml
import pathlib
import requests
from typing import List

# Ensure repo root on sys.path to import rag_idl from parent dir
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from omniORB import CORBA, PortableServer
import CosNaming

# Generated by omniidl from idl/rag.idl
import rag_idl
from rag_idl import _0_rag__POA as rag__POA  # POA classes
from rag_idl import _0_rag as rag            # interface types

# ---------- logging ----------

def setup_logging():
    with open(os.path.join(os.path.dirname(__file__), "..", "common", "logging.yaml")) as f:
        logging.config.dictConfig(yaml.safe_load(f))

log = logging.getLogger("worker")

# ---------- PDF text extraction ----------

def extract_text_pdfminer(pdf_path: str) -> str:
    from pdfminer.high_level import extract_text
    return extract_text(pdf_path)

# ---------- chunking (fixed window with overlap) ----------

def normalize_whitespace(s: str) -> str:
    return " ".join(s.split())

def chunk_text(s: str, max_chars: int = 1500, overlap: int = 250) -> List[str]:
    clean = normalize_whitespace(s)
    out: List[str] = []
    i = 0
    while i < len(clean):
        end = min(i + max_chars, len(clean))
        slice_ = clean[i:end]
        # Try to cut at a sentence boundary near the end
        cut = slice_.rfind(". ")
        if cut >= int(max_chars * 0.6):
            piece = slice_[:cut+1]
        else:
            piece = slice_
        if piece:
            out.append(piece)
        step = max(len(piece) - overlap, 1)
        i += step
    return out

# ---------- Ollama embeddings ----------

def ollama_embed_single(text: str, model: str, base: str = None) -> List[float]:
    """
    Call Ollama /api/embeddings for a single string.
    Some builds need 'prompt', others accept 'input'—we'll use 'prompt' since it worked on your box.
    """
    base_url = base or os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434")
    url = f"{base_url}/api/embeddings"
    # use prompt key (your earlier tests showed it returns {"embedding":[...]} )
    resp = requests.post(url, json={"model": model, "prompt": text}, timeout=120)
    resp.raise_for_status()
    data = resp.json()
    vec = data.get("embedding") or []
    if not isinstance(vec, list) or not vec:
        raise RuntimeError(f"Ollama returned empty embedding for text (len={len(text)})")
    return vec

# ---------- Worker servant ----------

class WorkerServant(rag__POA.Worker):
    def ping(self):
        log.info("Ping received from coordinator.")

    def processFile(self, pdf_path, job_id, model, max_chars, overlap, out_dir):
        """
        Implements the IDL method:
          string processFile(in string pdf_path, in string job_id, in string model,
                             in long max_chars, in long overlap, in string out_dir);
        """
        start = time.time()
        log.info(f"[{job_id}] processFile start: pdf_path={pdf_path}, model={model}, "
                 f"max_chars={max_chars}, overlap={overlap}, out_dir={out_dir}")

        pdf_path = os.path.abspath(pdf_path)
        out_dir = os.path.abspath(out_dir)
        pathlib.Path(out_dir).mkdir(parents=True, exist_ok=True)

        if not os.path.exists(pdf_path):
            raise FileNotFoundError(f"PDF not found: {pdf_path}")

        # 1) Extract and chunk
        text = extract_text_pdfminer(pdf_path)
        chunks = chunk_text(text, max_chars=max(256, int(max_chars)), overlap=max(0, int(overlap)))
        log.info(f"[{job_id}] extracted text chars={len(text)}, chunks={len(chunks)}")

        # 2) Embed per chunk
        records = []
        doc_id = os.path.basename(pdf_path)
        for idx, ch in enumerate(chunks):
            try:
                vec = ollama_embed_single(ch, model=model)
            except Exception as e:
                log.error(f"[{job_id}] embedding failed for chunk {idx}: {e}")
                vec = []  # keep going; you can choose to raise instead
            rec = {
                "job_id": job_id,
                "doc_id": doc_id,
                "chunk_id": idx,
                "text": ch,
                "vec": vec,
                "model": model,
                "timestamp": int(time.time())
            }
            records.append(rec)
            if (idx + 1) % 5 == 0:
                log.info(f"[{job_id}] embedded {idx + 1}/{len(chunks)} chunks")

        # 3) Write JSONL
        out_path = os.path.join(out_dir, f"{job_id}.jsonl")
        with open(out_path, "w", encoding="utf-8") as f:
            for rec in records:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")

        dur = time.time() - start
        log.info(f"[{job_id}] wrote {len(records)} records to {out_path} in {dur:.1f}s")
        return out_path

def ensure_context(root: CosNaming.NamingContext, id_str: str) -> CosNaming.NamingContext:
    name = [CosNaming.NameComponent(id_str, "")]
    try:
        ctx = root.resolve(name)
        return ctx._narrow(CosNaming.NamingContext)
    except CosNaming.NamingContext.NotFound:
        return root.bind_new_context(name)

def main():
    setup_logging()
    # Pass NameService explicitly
    orb = CORBA.ORB_init(
        sys.argv + ["-ORBInitRef", "NameService=corbaname::127.0.0.1:2809"],
        CORBA.ORB_ID
    )
    poa = orb.resolve_initial_references("RootPOA")
    poa_manager = poa._get_the_POAManager()

    servant = WorkerServant()
    poa.activate_object(servant)
    ref = servant._this()

    root = orb.resolve_initial_references("NameService")._narrow(CosNaming.NamingContext)
    rag_ctx = ensure_context(root, "RagWorker")
    name = [CosNaming.NameComponent("worker-001", "")]
    try:
        rag_ctx.bind(name, ref)
    except CosNaming.NamingContext.AlreadyBound:
        rag_ctx.rebind(name, ref)

    logging.getLogger("worker").info("Worker ready as RagWorker/worker-001")
    poa_manager.activate()
    orb.run()

if __name__ == "__main__":
    main()
